### ISSUE TITLE
Please add some information for ios_product_price_map_sample.csv

### ISSUE THREAD

**Issue by anhtuank7c** [RevenueCat-Samples/import-csv-samples#3]
Hi @mshmoustafa 
Could you add some explanation for some properties of `ios_product_price_map_sample`
ie:
- What does `date`, `duration` up for?
- Is there any pattern code for `duraction`? ie weekly should be P1W, monthly should be P1M, each 6 months should be P6M, and how about annual plan? should it be `P1Y`?
- If my monthly subscription plan have 01 week for free, should it fill `0` to introductory_price?
- The prices for first year and the second years looks different. What should I choose (1)

![Screen Shot 2021-12-22 at 09 34 22](https://user-images.githubusercontent.com/3163410/147028172-923fc100-7db2-4c14-b38e-d802fe23a4fa.png)
![Screen Shot 2021-12-22 at 09 59 30](https://user-images.githubusercontent.com/3163410/147028181-9c5b38dd-671d-4676-bf5d-f3b88f02815e.png)

**Comment by mshmoustafa** [comment]
Hi @anhtuank7c, thanks for raising this issue, these are all fair points.
- The `date` is the date that the price was effective. This property is useful if a product has had different prices over its life. For example, if you initially created a product at $4.99 per month on November 10, but then raised the price of the product on December 10 to $8.99, then you would have two rows in the product price map file for this product:
```
product_id,price,currency,introductory_price,date,duration
my_monthly_product,4.99,USD,0.99,2021-11-10,P1M
my_monthly_product,8.99,USD,0.99,2021-12-10,P1M
```
- The `duration` is the billing cycle duration of a normal billing period. So if you offer 1 month subscription with a 1 week trial period, the duration would be `P1M` because the normal billing period is 1 month.
- `P1Y` is correct for a 1-year subscription. The duration is a [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations).
> If my monthly subscription plan have 01 week for free, should it fill 0 to introductory_price?
- Yes, that's exactly correct. RevenueCat will interpret `introductory_price=0` as a free trial. There's an issue with the sample that I will fix - if you include an introductory_price, you must also include a introductory_price_duration column with the duration of the intro price. So for your product that is a monthly subscription with 1 week free, the row would look like this:
```
product_id,price,currency,introductory_price,date,duration,introductory_price_duration
my_monthly_product,4.99,USD,0.99,2021-11-10,P1M,P1W
```
I will submit a PR to get this fixed.
> The prices for first year and the second years looks different. What should I choose (1)
- We need the full price of the product, not the proceeds. So in both of your screenshots, we need the price that's in the Price column (not the Proceeds columns.) So for Afghanistan, you would put $5.99, not $5.09.

So here's a complete example:

- Consider a `premium_upgrade` product was created on October 19 2021.
- It's a 6-month subscription with a 1-month free trial.
- It's price is $3.99 in the USA but the price was changed to $6.99 on December 13.

The product price map would look like this:

```
product_id,price,currency,introductory_price,date,duration,introductory_price_duration
premium_upgrade,3.99,USD,0.00,2021-10-19,P6M,P1M
premium_upgrade,6.99,USD,0.00,2021-12-13,P6M,P1M
...
```

You can add rows for as many currencies as you'd like. For instance, if your product is popular in India, you can add more rows with INR as the currency:

```
product_id,price,currency,introductory_price,date,duration,introductory_price_duration
premium_upgrade,3.99,USD,0.00,2021-10-19,P6M,P1M
premium_upgrade,6.99,USD,0.00,2021-12-13,P6M,P1M
premium_upgrade,300,INR,0.00,2021-10-19,P6M,P1M
premium_upgrade,500,INR,0.00,2021-12-13,P6M,P1M
`...`
```

**Comment by anhtuank7c** [comment]
@mshmoustafa Thank you so much.
